
on: [push]

# Environment variables available to all jobs and steps in this workflow
env:
  REGISTRY_NAME: githubactionstesting.azurecr.io
  CLUSTER_NAME: githubactionsdeploymenttestingcluster
  CLUSTER_RESOURCE_GROUP: gitHub-actions-testing-rg
  APP_NAME: helloaspnetcore
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
        
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/${{ github.repository }}
        tags: latest 
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
          client-id: 85fc087d-f183-431d-a3a6-395a27d13cb7
          tenant-id: 3d6ad08e-958e-4f7e-af5b-2517eb6dad60
          subscription-id: 3c47d766-d2f9-4d07-9df4-3536ba1fa932
         
    # Connect to Azure Container Registry (ACR)
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}
        username: ${{ secrets.REGISTRY_USERNAME }} 
        password: ${{ secrets.REGISTRY_PASSWORD }}
    # Container build and push to a Azure Container Registry (ACR)
    - run: |
        docker build . -t ${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }}:${{ github.sha }}
        docker push ${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }}:${{ github.sha }}
    
