
on: [push]

# Environment variables available to all jobs and steps in this workflow
env:
  REGISTRY_NAME: githubtestingrg.azurecr.io
  CLUSTER_NAME: githubactionsdeploymenttestingcluster
  CLUSTER_RESOURCE_GROUP: gitHub-actions-testing-rg
  APP_NAME: helloaspnetcore
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
           
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    # Connect to Azure Container Registry (ACR)
    - name: Build and push
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}
        username: ${{ secrets.REGISTRY_USERNAME }} 
        password: ${{ secrets.REGISTRY_PASSWORD }}
    # Container build and push to a Azure Container Registry (ACR)
    - run: |
        docker build . -t ${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }}:${{ github.sha }}
        docker push ${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }}:${{ github.sha }}
    
